-- StockFlow B2B - PostgreSQL schema for Supabase
-- Run once on a new Supabase project from Dashboard > SQL Editor.
-- Authentication is handled by Supabase Auth. This migration creates the
-- application profile, business workflow, RLS policies, RPC functions,
-- notifications, and Storage buckets/policies.

begin;

create extension if not exists pgcrypto;

-- =========================================================
-- 1. ENUMS
-- =========================================================

do $$ begin
  create type public.app_role as enum ('host', 'seller', 'customer', 'carrier');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.listing_status as enum (
    'draft', 'pending_review', 'approved', 'rejected', 'paused', 'sold_out'
  );
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.media_type as enum ('image', 'document');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.purchase_request_status as enum (
    'submitted',
    'host_review',
    'awaiting_seller_confirmation',
    'seller_confirmed',
    'seller_rejected',
    'awaiting_logistics_quote',
    'quoted',
    'buyer_confirmed',
    'cancelled',
    'converted_to_order'
  );
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.quote_status as enum ('requested', 'submitted', 'accepted', 'rejected', 'expired');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.order_status as enum (
    'awaiting_payment', 'confirmed', 'pickup_scheduled', 'picked_up',
    'in_transit', 'delivered', 'completed', 'cancelled', 'disputed'
  );
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.shipment_status as enum (
    'quote_requested', 'quoted', 'scheduled', 'picked_up',
    'in_transit', 'delivered', 'cancelled'
  );
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.payment_type as enum ('goods', 'shipping', 'platform_fee');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.payment_status as enum ('pending', 'paid', 'failed', 'refunded');
exception when duplicate_object then null;
end $$;

-- =========================================================
-- 2. CORE USER / COMPANY TABLES
-- =========================================================

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  tax_code text,
  phone text,
  email text,
  address text,
  city text,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint organizations_name_not_blank check (length(trim(name)) > 0)
);

create unique index if not exists organizations_tax_code_unique
  on public.organizations (lower(tax_code))
  where tax_code is not null and trim(tax_code) <> '';

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  phone text,
  avatar_url text,
  role public.app_role not null default 'customer',
  organization_id uuid references public.organizations(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists profiles_organization_idx on public.profiles(organization_id);

create table if not exists public.warehouses (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  contact_name text,
  contact_phone text,
  address text not null,
  city text not null,
  district text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint warehouses_name_not_blank check (length(trim(name)) > 0),
  constraint warehouses_address_not_blank check (length(trim(address)) > 0)
);

create index if not exists warehouses_organization_idx on public.warehouses(organization_id);

-- =========================================================
-- 3. PRODUCT LISTINGS
-- =========================================================

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.categories(name, slug)
values
  ('Bao bì và vật tư đóng gói', 'bao-bi-vat-tu-dong-goi'),
  ('Vải và phụ liệu may mặc', 'vai-phu-lieu-may-mac'),
  ('Nông sản khô và thực phẩm đóng gói', 'nong-san-kho-thuc-pham-dong-goi')
on conflict (slug) do nothing;

create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.profiles(id) on delete restrict,
  seller_organization_id uuid not null references public.organizations(id) on delete restrict,
  warehouse_id uuid not null references public.warehouses(id) on delete restrict,
  category_id bigint not null references public.categories(id) on delete restrict,
  product_name text not null,
  description text,
  quantity numeric(14,3) not null,
  reserved_quantity numeric(14,3) not null default 0,
  available_quantity numeric(14,3)
    generated always as (greatest(quantity - reserved_quantity, 0)) stored,
  unit text not null,
  unit_price numeric(18,2),
  negotiable boolean not null default false,
  condition_text text,
  manufacturing_date date,
  expiry_date date,
  lot_number text,
  document_notes text,
  location_text text not null,
  status public.listing_status not null default 'pending_review',
  rejection_reason text,
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint listings_product_name_not_blank check (length(trim(product_name)) > 0),
  constraint listings_quantity_positive check (quantity > 0),
  constraint listings_reserved_valid check (reserved_quantity >= 0 and reserved_quantity <= quantity),
  constraint listings_unit_not_blank check (length(trim(unit)) > 0),
  constraint listings_price_valid check (unit_price is null or unit_price >= 0),
  constraint listings_dates_valid check (
    expiry_date is null or manufacturing_date is null or expiry_date >= manufacturing_date
  )
);

create index if not exists listings_status_idx on public.listings(status);
create index if not exists listings_seller_idx on public.listings(seller_id);
create index if not exists listings_category_idx on public.listings(category_id);
create index if not exists listings_location_idx on public.listings(location_text);
create index if not exists listings_created_at_idx on public.listings(created_at desc);

create table if not exists public.listing_media (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  uploaded_by uuid not null references public.profiles(id) on delete restrict,
  media_type public.media_type not null,
  storage_bucket text not null,
  storage_path text not null,
  original_filename text,
  created_at timestamptz not null default now(),
  unique(storage_bucket, storage_path)
);

create index if not exists listing_media_listing_idx on public.listing_media(listing_id);

-- =========================================================
-- 4. PURCHASE REQUEST / LOGISTICS / ORDER FLOW
-- =========================================================

create table if not exists public.purchase_requests (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete restrict,
  buyer_id uuid not null references public.profiles(id) on delete restrict,
  buyer_organization_id uuid not null references public.organizations(id) on delete restrict,
  buyer_warehouse_id uuid not null references public.warehouses(id) on delete restrict,
  seller_id uuid not null references public.profiles(id) on delete restrict,
  host_id uuid references public.profiles(id) on delete set null,
  requested_quantity numeric(14,3) not null,
  proposed_unit_price numeric(18,2),
  seller_confirmed_quantity numeric(14,3),
  agreed_unit_price numeric(18,2),
  buyer_note text,
  seller_note text,
  host_note text,
  status public.purchase_request_status not null default 'submitted',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  seller_confirmed_at timestamptz,
  buyer_confirmed_at timestamptz,
  constraint purchase_requests_qty_positive check (requested_quantity > 0),
  constraint purchase_requests_price_valid check (proposed_unit_price is null or proposed_unit_price >= 0),
  constraint purchase_requests_seller_qty_valid check (
    seller_confirmed_quantity is null or seller_confirmed_quantity > 0
  ),
  constraint purchase_requests_agreed_price_valid check (agreed_unit_price is null or agreed_unit_price >= 0)
);

create index if not exists purchase_requests_listing_idx on public.purchase_requests(listing_id);
create index if not exists purchase_requests_buyer_idx on public.purchase_requests(buyer_id);
create index if not exists purchase_requests_seller_idx on public.purchase_requests(seller_id);
create index if not exists purchase_requests_host_idx on public.purchase_requests(host_id);
create index if not exists purchase_requests_status_idx on public.purchase_requests(status);

create table if not exists public.logistics_partners (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contact_name text,
  phone text,
  email text,
  address text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint logistics_partners_name_not_blank check (length(trim(name)) > 0)
);

create table if not exists public.logistics_quotes (
  id uuid primary key default gen_random_uuid(),
  purchase_request_id uuid not null references public.purchase_requests(id) on delete cascade,
  logistics_partner_id uuid not null references public.logistics_partners(id) on delete restrict,
  created_by uuid not null references public.profiles(id) on delete restrict,
  shipping_fee numeric(18,2) not null,
  loading_fee numeric(18,2) not null default 0,
  count_fee numeric(18,2) not null default 0,
  duration_text text,
  estimated_pickup_at timestamptz,
  estimated_delivery_at timestamptz,
  valid_until timestamptz,
  note text,
  status public.quote_status not null default 'submitted',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint logistics_quotes_fee_valid check (shipping_fee >= 0),
  constraint logistics_quotes_loading_fee_valid check (loading_fee >= 0),
  constraint logistics_quotes_count_fee_valid check (count_fee >= 0),
  constraint logistics_quotes_dates_valid check (
    estimated_delivery_at is null or estimated_pickup_at is null
    or estimated_delivery_at >= estimated_pickup_at
  )
);

create index if not exists logistics_quotes_request_idx
  on public.logistics_quotes(purchase_request_id);

alter table public.purchase_requests
  add column if not exists selected_logistics_quote_id uuid
  references public.logistics_quotes(id) on delete set null;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default (
    'SF-' || to_char(now(), 'YYYYMMDD') || '-' ||
    upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))
  ),
  purchase_request_id uuid not null unique references public.purchase_requests(id) on delete restrict,
  listing_id uuid not null references public.listings(id) on delete restrict,
  seller_id uuid not null references public.profiles(id) on delete restrict,
  buyer_id uuid not null references public.profiles(id) on delete restrict,
  host_id uuid not null references public.profiles(id) on delete restrict,
  logistics_quote_id uuid not null references public.logistics_quotes(id) on delete restrict,
  quantity numeric(14,3) not null,
  unit text not null,
  unit_price numeric(18,2) not null,
  goods_amount numeric(18,2) not null,
  shipping_fee numeric(18,2) not null,
  platform_fee numeric(18,2) not null default 0,
  total_amount numeric(18,2)
    generated always as (goods_amount + shipping_fee + platform_fee) stored,
  pickup_address_snapshot text not null,
  delivery_address_snapshot text not null,
  status public.order_status not null default 'awaiting_payment',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint orders_qty_positive check (quantity > 0),
  constraint orders_amounts_valid check (
    unit_price >= 0 and goods_amount >= 0 and shipping_fee >= 0 and platform_fee >= 0
  )
);

create index if not exists orders_buyer_idx on public.orders(buyer_id);
create index if not exists orders_seller_idx on public.orders(seller_id);
create index if not exists orders_host_idx on public.orders(host_id);
create index if not exists orders_status_idx on public.orders(status);

create table if not exists public.shipments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  logistics_partner_id uuid not null references public.logistics_partners(id) on delete restrict,
  tracking_code text,
  status public.shipment_status not null default 'scheduled',
  scheduled_pickup_at timestamptz,
  picked_up_at timestamptz,
  delivered_at timestamptz,
  proof_of_delivery_path text,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shipment_events (
  id bigint generated by default as identity primary key,
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  status public.shipment_status not null,
  message text,
  location_text text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists shipment_events_shipment_idx
  on public.shipment_events(shipment_id, created_at desc);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  payer_id uuid not null references public.profiles(id) on delete restrict,
  payment_type public.payment_type not null,
  amount numeric(18,2) not null,
  status public.payment_status not null default 'pending',
  beneficiary_name text not null,
  transaction_reference text,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payments_amount_valid check (amount >= 0),
  unique(order_id, payment_type)
);

create index if not exists payments_order_idx on public.payments(order_id);
create index if not exists payments_status_idx on public.payments(status);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  message text not null,
  entity_type text,
  entity_id uuid,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_idx
  on public.notifications(user_id, created_at desc);

-- =========================================================
-- 5. HELPER FUNCTIONS
-- =========================================================

create or replace function public.current_app_role()
returns public.app_role
language sql
stable
security definer
set search_path = public
as $$
  select p.role from public.profiles p where p.id = (select auth.uid());
$$;

create or replace function public.is_host()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_app_role() = 'host'::public.app_role, false);
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_role text;
  safe_role public.app_role;
begin
  requested_role := lower(coalesce(new.raw_user_meta_data ->> 'role', 'customer'));

  -- Public signup can only create seller/customer accounts.
  -- Host must be assigned manually by an existing host or SQL/service role.
  safe_role := case
    when requested_role = 'seller' then 'seller'::public.app_role
    else 'customer'::public.app_role
  end;

  insert into public.profiles(id, email, full_name, phone, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.raw_user_meta_data ->> 'phone',
    safe_role
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();

create or replace function public.protect_profile_privileges()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.role is distinct from new.role
     and (select auth.uid()) is not null
     and not public.is_host() then
    raise exception 'Only a host can change application roles';
  end if;

  if old.is_active is distinct from new.is_active
     and (select auth.uid()) is not null
     and not public.is_host() then
    raise exception 'Only a host can activate or deactivate accounts';
  end if;

  if old.organization_id is distinct from new.organization_id
     and new.organization_id is not null
     and (select auth.uid()) is not null
     and not public.is_host()
     and not exists (
       select 1
       from public.organizations o
       where o.id = new.organization_id
         and o.created_by = (select auth.uid())
     ) then
    raise exception 'You can only join an organization that you created';
  end if;

  return new;
end;
$$;

drop trigger if exists protect_profile_privileges_trigger on public.profiles;
create trigger protect_profile_privileges_trigger
  before update on public.profiles
  for each row execute function public.protect_profile_privileges();

create or replace function public.enforce_listing_rules()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_host() then
    if tg_op = 'INSERT' then
      new.seller_id := (select auth.uid());
      new.reserved_quantity := 0;
      if new.status not in ('draft'::public.listing_status, 'pending_review'::public.listing_status) then
        new.status := 'pending_review';
      end if;
      new.approved_by := null;
      new.approved_at := null;
      new.rejection_reason := null;
    else
      new.created_at := old.created_at;
      new.reserved_quantity := old.reserved_quantity;

      if new.seller_id <> old.seller_id then
        raise exception 'Seller cannot transfer listing ownership';
      end if;

      if new.status is distinct from old.status
         and new.status in (
           'approved'::public.listing_status,
           'rejected'::public.listing_status,
           'sold_out'::public.listing_status
         ) then
        raise exception 'Only a host can set this listing status';
      end if;

      if old.status = 'approved'::public.listing_status
         and (
           new.product_name is distinct from old.product_name or
           new.description is distinct from old.description or
           new.quantity is distinct from old.quantity or
           new.unit is distinct from old.unit or
           new.unit_price is distinct from old.unit_price or
           new.condition_text is distinct from old.condition_text or
           new.manufacturing_date is distinct from old.manufacturing_date or
           new.expiry_date is distinct from old.expiry_date or
           new.warehouse_id is distinct from old.warehouse_id or
           new.category_id is distinct from old.category_id
         ) then
        new.status := 'pending_review';
        new.approved_by := null;
        new.approved_at := null;
        new.rejection_reason := null;
      else
        new.approved_by := old.approved_by;
        new.approved_at := old.approved_at;
        new.rejection_reason := old.rejection_reason;
      end if;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_listing_rules_trigger on public.listings;
create trigger enforce_listing_rules_trigger
  before insert or update on public.listings
  for each row execute function public.enforce_listing_rules();

create or replace function public.prepare_purchase_request()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_listing public.listings%rowtype;
  buyer_org uuid;
begin
  if public.current_app_role() <> 'customer'::public.app_role then
    raise exception 'Only customer accounts can create purchase requests';
  end if;

  select * into target_listing
  from public.listings
  where id = new.listing_id
  for update;

  if not found or target_listing.status <> 'approved'::public.listing_status then
    raise exception 'Listing is not available for purchase';
  end if;

  if new.requested_quantity > target_listing.available_quantity then
    raise exception 'Requested quantity exceeds available quantity';
  end if;

  select organization_id into buyer_org
  from public.profiles
  where id = (select auth.uid());

  if buyer_org is null then
    raise exception 'Buyer must create and attach an organization first';
  end if;

  if not exists (
    select 1 from public.warehouses w
    where w.id = new.buyer_warehouse_id and w.organization_id = buyer_org
  ) then
    raise exception 'Delivery warehouse does not belong to the buyer organization';
  end if;

  new.buyer_id := (select auth.uid());
  new.buyer_organization_id := buyer_org;
  new.seller_id := target_listing.seller_id;
  new.proposed_unit_price := coalesce(new.proposed_unit_price, target_listing.unit_price);
  new.status := 'submitted';
  new.host_id := null;

  return new;
end;
$$;

drop trigger if exists prepare_purchase_request_trigger on public.purchase_requests;
create trigger prepare_purchase_request_trigger
  before insert on public.purchase_requests
  for each row execute function public.prepare_purchase_request();

create or replace function public.notify_user(
  p_user_id uuid,
  p_title text,
  p_message text,
  p_entity_type text default null,
  p_entity_id uuid default null
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.notifications(user_id, title, message, entity_type, entity_id)
  values (p_user_id, p_title, p_message, p_entity_type, p_entity_id);
$$;

create or replace function public.notify_hosts(
  p_title text,
  p_message text,
  p_entity_type text default null,
  p_entity_id uuid default null
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.notifications(user_id, title, message, entity_type, entity_id)
  select id, p_title, p_message, p_entity_type, p_entity_id
  from public.profiles
  where role = 'host'::public.app_role and is_active = true;
$$;

create or replace function public.after_listing_created_notify()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'pending_review'::public.listing_status then
    perform public.notify_hosts(
      'Listing mới cần kiểm duyệt',
      'Seller vừa đăng: ' || new.product_name,
      'listing',
      new.id
    );
  end if;
  return new;
end;
$$;

drop trigger if exists after_listing_created_notify_trigger on public.listings;
create trigger after_listing_created_notify_trigger
  after insert on public.listings
  for each row execute function public.after_listing_created_notify();

create or replace function public.after_purchase_request_created_notify()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.notify_hosts(
    'Yêu cầu mua mới',
    'Buyer đã gửi một yêu cầu mua cần tiếp nhận.',
    'purchase_request',
    new.id
  );
  return new;
end;
$$;

drop trigger if exists after_purchase_request_created_notify_trigger on public.purchase_requests;
create trigger after_purchase_request_created_notify_trigger
  after insert on public.purchase_requests
  for each row execute function public.after_purchase_request_created_notify();

-- =========================================================
-- 6. WORKFLOW RPC FUNCTIONS
-- Call these from the frontend instead of directly changing sensitive states.
-- =========================================================

create or replace function public.host_review_listing(
  p_listing_id uuid,
  p_approve boolean,
  p_reason text default null
)
returns public.listings
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.listings;
begin
  if not public.is_host() then
    raise exception 'Host permission required';
  end if;

  update public.listings
  set
    status = case when p_approve then 'approved'::public.listing_status
                  else 'rejected'::public.listing_status end,
    approved_by = case when p_approve then (select auth.uid()) else null end,
    approved_at = case when p_approve then now() else null end,
    rejection_reason = case when p_approve then null else nullif(trim(p_reason), '') end
  where id = p_listing_id
  returning * into result;

  if not found then
    raise exception 'Listing not found';
  end if;

  perform public.notify_user(
    result.seller_id,
    case when p_approve then 'Listing đã được duyệt' else 'Listing bị từ chối' end,
    case when p_approve then 'Sản phẩm đã hiển thị trên marketplace.'
         else coalesce(result.rejection_reason, 'Vui lòng kiểm tra và cập nhật thông tin.') end,
    'listing',
    result.id
  );

  return result;
end;
$$;

create or replace function public.host_assign_purchase_request(p_request_id uuid)
returns public.purchase_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.purchase_requests;
begin
  if not public.is_host() then
    raise exception 'Host permission required';
  end if;

  update public.purchase_requests
  set host_id = (select auth.uid()),
      status = 'awaiting_seller_confirmation'
  where id = p_request_id
    and status in ('submitted', 'host_review')
  returning * into result;

  if not found then
    raise exception 'Request not found or cannot be assigned';
  end if;

  perform public.notify_user(
    result.seller_id,
    'Có yêu cầu mua cần xác nhận',
    'StockFlow đang liên hệ để xác nhận số lượng và khả năng cung cấp.',
    'purchase_request',
    result.id
  );

  return result;
end;
$$;

create or replace function public.seller_respond_purchase_request(
  p_request_id uuid,
  p_accept boolean,
  p_confirmed_quantity numeric default null,
  p_agreed_unit_price numeric default null,
  p_note text default null
)
returns public.purchase_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  req public.purchase_requests;
  available_qty numeric;
  locked_row record;
begin
  select pr as purchase_request, l.available_quantity
  into locked_row
  from public.purchase_requests pr
  join public.listings l on l.id = pr.listing_id
  where pr.id = p_request_id
  for update of pr, l;

  if not found then
    raise exception 'Purchase request not found';
  end if;

  req := locked_row.purchase_request;
  available_qty := locked_row.available_quantity;

  if req.seller_id <> (select auth.uid()) then
    raise exception 'Only the listing seller can respond';
  end if;

  if req.status not in (
    'submitted'::public.purchase_request_status,
    'host_review'::public.purchase_request_status,
    'awaiting_seller_confirmation'::public.purchase_request_status
  ) then
    raise exception 'Purchase request is not awaiting seller response';
  end if;

  if p_accept then
    if p_confirmed_quantity is null or p_confirmed_quantity <= 0 then
      raise exception 'Confirmed quantity must be positive';
    end if;
    if p_confirmed_quantity > req.requested_quantity or p_confirmed_quantity > available_qty then
      raise exception 'Confirmed quantity is invalid';
    end if;
  end if;

  update public.purchase_requests
  set
    status = case when p_accept
                  then 'seller_confirmed'::public.purchase_request_status
                  else 'seller_rejected'::public.purchase_request_status end,
    seller_confirmed_quantity = case when p_accept then p_confirmed_quantity else null end,
    agreed_unit_price = case when p_accept
                             then coalesce(p_agreed_unit_price, req.proposed_unit_price)
                             else null end,
    seller_note = p_note,
    seller_confirmed_at = now()
  where id = p_request_id
  returning * into req;

  if req.host_id is not null then
    perform public.notify_user(
      req.host_id,
      case when p_accept then 'Seller đã xác nhận hàng' else 'Seller từ chối yêu cầu' end,
      coalesce(p_note, 'Đã cập nhật trạng thái yêu cầu mua.'),
      'purchase_request',
      req.id
    );
  else
    perform public.notify_hosts(
      case when p_accept then 'Seller đã xác nhận hàng' else 'Seller từ chối yêu cầu' end,
      coalesce(p_note, 'Đã cập nhật trạng thái yêu cầu mua.'),
      'purchase_request',
      req.id
    );
  end if;

  perform public.notify_user(
    req.buyer_id,
    case when p_accept then 'Seller đã xác nhận hàng' else 'Seller không thể cung cấp hàng' end,
    coalesce(p_note, 'Yêu cầu mua đã được cập nhật.'),
    'purchase_request',
    req.id
  );

  return req;
end;
$$;

create or replace function public.host_add_logistics_quote(
  p_request_id uuid,
  p_logistics_partner_id uuid,
  p_shipping_fee numeric,
  p_estimated_pickup_at timestamptz default null,
  p_estimated_delivery_at timestamptz default null,
  p_valid_until timestamptz default null,
  p_note text default null
)
returns public.logistics_quotes
language plpgsql
security definer
set search_path = public
as $$
declare
  quote_row public.logistics_quotes;
  req public.purchase_requests;
begin
  if not public.is_host() then
    raise exception 'Host permission required';
  end if;

  if p_shipping_fee < 0 then
    raise exception 'Shipping fee cannot be negative';
  end if;

  select * into req
  from public.purchase_requests
  where id = p_request_id
  for update;

  if not found or req.status not in (
    'seller_confirmed'::public.purchase_request_status,
    'awaiting_logistics_quote'::public.purchase_request_status,
    'quoted'::public.purchase_request_status
  ) then
    raise exception 'Request is not ready for a logistics quote';
  end if;

  insert into public.logistics_quotes(
    purchase_request_id, logistics_partner_id, created_by,
    shipping_fee, estimated_pickup_at, estimated_delivery_at,
    valid_until, note, status
  ) values (
    p_request_id, p_logistics_partner_id, (select auth.uid()),
    p_shipping_fee, p_estimated_pickup_at, p_estimated_delivery_at,
    p_valid_until, p_note, 'submitted'
  ) returning * into quote_row;

  update public.purchase_requests
  set host_id = coalesce(host_id, (select auth.uid())),
      status = 'quoted'
  where id = p_request_id;

  perform public.notify_user(
    req.buyer_id,
    'Đã có báo giá vận chuyển',
    'Vui lòng kiểm tra và xác nhận tổng chi phí giao dịch.',
    'logistics_quote',
    quote_row.id
  );

  return quote_row;
end;
$$;

create or replace function public.buyer_confirm_logistics_quote(
  p_request_id uuid,
  p_quote_id uuid
)
returns public.purchase_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  req public.purchase_requests;
begin
  select * into req
  from public.purchase_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception 'Purchase request not found';
  end if;

  if req.buyer_id <> (select auth.uid()) then
    raise exception 'Only the buyer can confirm this quote';
  end if;

  if req.status <> 'quoted'::public.purchase_request_status then
    raise exception 'Request is not awaiting buyer confirmation';
  end if;

  if not exists (
    select 1 from public.logistics_quotes q
    where q.id = p_quote_id
      and q.purchase_request_id = p_request_id
      and q.status = 'submitted'::public.quote_status
      and (q.valid_until is null or q.valid_until >= now())
  ) then
    raise exception 'Quote is invalid or expired';
  end if;

  update public.logistics_quotes
  set status = case when id = p_quote_id
                    then 'accepted'::public.quote_status
                    else 'rejected'::public.quote_status end
  where purchase_request_id = p_request_id
    and status = 'submitted'::public.quote_status;

  update public.purchase_requests
  set selected_logistics_quote_id = p_quote_id,
      status = 'buyer_confirmed',
      buyer_confirmed_at = now()
  where id = p_request_id
  returning * into req;

  if req.host_id is not null then
    perform public.notify_user(
      req.host_id,
      'Buyer đã xác nhận giao dịch',
      'Có thể tạo đơn hàng và điều phối lấy hàng.',
      'purchase_request',
      req.id
    );
  else
    perform public.notify_hosts(
      'Buyer đã xác nhận giao dịch',
      'Có thể tạo đơn hàng và điều phối lấy hàng.',
      'purchase_request',
      req.id
    );
  end if;

  return req;
end;
$$;

create or replace function public.buyer_cancel_purchase_request(
  p_request_id uuid,
  p_note text default null
)
returns public.purchase_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  req public.purchase_requests;
begin
  update public.purchase_requests
  set status = 'cancelled',
      buyer_note = concat_ws(E'\n', buyer_note, nullif(trim(p_note), ''))
  where id = p_request_id
    and buyer_id = (select auth.uid())
    and status not in ('converted_to_order', 'cancelled')
  returning * into req;

  if not found then
    raise exception 'Request cannot be cancelled';
  end if;

  perform public.notify_user(
    req.seller_id,
    'Buyer đã hủy yêu cầu mua',
    coalesce(p_note, 'Yêu cầu mua đã bị hủy.'),
    'purchase_request',
    req.id
  );

  if req.host_id is not null then
    perform public.notify_user(
      req.host_id,
      'Buyer đã hủy yêu cầu mua',
      coalesce(p_note, 'Yêu cầu mua đã bị hủy.'),
      'purchase_request',
      req.id
    );
  end if;

  return req;
end;
$$;

create or replace function public.host_create_order(
  p_request_id uuid,
  p_platform_fee numeric default 0
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  req public.purchase_requests;
  listing_row public.listings;
  quote_row public.logistics_quotes;
  seller_warehouse public.warehouses;
  buyer_warehouse public.warehouses;
  seller_org public.organizations;
  partner public.logistics_partners;
  order_row public.orders;
  goods_total numeric(18,2);
begin
  if not public.is_host() then
    raise exception 'Host permission required';
  end if;

  if p_platform_fee < 0 then
    raise exception 'Platform fee cannot be negative';
  end if;

  select * into req
  from public.purchase_requests
  where id = p_request_id
  for update;

  if not found or req.status <> 'buyer_confirmed'::public.purchase_request_status then
    raise exception 'Request is not ready to become an order';
  end if;

  select * into listing_row
  from public.listings
  where id = req.listing_id
  for update;

  if req.seller_confirmed_quantity is null
     or req.seller_confirmed_quantity > listing_row.available_quantity then
    raise exception 'Insufficient available stock';
  end if;

  if req.agreed_unit_price is null then
    raise exception 'Agreed unit price is required';
  end if;

  select * into quote_row
  from public.logistics_quotes
  where id = req.selected_logistics_quote_id
    and purchase_request_id = req.id
    and status = 'accepted';

  if not found then
    raise exception 'Accepted logistics quote not found';
  end if;

  select * into seller_warehouse from public.warehouses where id = listing_row.warehouse_id;
  select * into buyer_warehouse from public.warehouses where id = req.buyer_warehouse_id;
  select * into seller_org from public.organizations where id = listing_row.seller_organization_id;
  select * into partner from public.logistics_partners where id = quote_row.logistics_partner_id;

  goods_total := round(req.seller_confirmed_quantity * req.agreed_unit_price, 2);

  insert into public.orders(
    purchase_request_id, listing_id, seller_id, buyer_id, host_id,
    logistics_quote_id, quantity, unit, unit_price, goods_amount,
    shipping_fee, platform_fee, pickup_address_snapshot,
    delivery_address_snapshot, status
  ) values (
    req.id, listing_row.id, req.seller_id, req.buyer_id, (select auth.uid()),
    quote_row.id, req.seller_confirmed_quantity, listing_row.unit,
    req.agreed_unit_price, goods_total, quote_row.shipping_fee,
    p_platform_fee,
    concat_ws(', ', seller_warehouse.name, seller_warehouse.address,
              seller_warehouse.district, seller_warehouse.city),
    concat_ws(', ', buyer_warehouse.name, buyer_warehouse.address,
              buyer_warehouse.district, buyer_warehouse.city),
    'awaiting_payment'
  ) returning * into order_row;

  update public.listings
  set reserved_quantity = reserved_quantity + order_row.quantity
  where id = listing_row.id;

  insert into public.shipments(
    order_id, logistics_partner_id, status,
    scheduled_pickup_at, note
  ) values (
    order_row.id, quote_row.logistics_partner_id, 'scheduled',
    quote_row.estimated_pickup_at, quote_row.note
  );

  insert into public.payments(order_id, payer_id, payment_type, amount, beneficiary_name)
  values
    (order_row.id, order_row.buyer_id, 'goods', order_row.goods_amount, seller_org.name),
    (order_row.id, order_row.buyer_id, 'shipping', order_row.shipping_fee, partner.name),
    (order_row.id, order_row.buyer_id, 'platform_fee', order_row.platform_fee, 'StockFlow');

  update public.purchase_requests
  set status = 'converted_to_order', host_id = (select auth.uid())
  where id = req.id;

  perform public.notify_user(
    order_row.buyer_id,
    'Đơn hàng đã được tạo',
    'Vui lòng hoàn tất các khoản thanh toán theo đơn ' || order_row.order_number || '.',
    'order', order_row.id
  );

  perform public.notify_user(
    order_row.seller_id,
    'Đơn hàng đã được xác nhận',
    'Vui lòng chuẩn bị hàng để đối tác logistics đến nhận.',
    'order', order_row.id
  );

  return order_row;
end;
$$;

create or replace function public.sync_inventory_after_order_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.status <> 'cancelled'::public.order_status
     and new.status = 'cancelled'::public.order_status
     and old.status <> 'completed'::public.order_status then
    update public.listings
    set reserved_quantity = greatest(reserved_quantity - new.quantity, 0)
    where id = new.listing_id;
  end if;

  if old.status <> 'completed'::public.order_status
     and new.status = 'completed'::public.order_status then
    update public.listings
    set quantity = greatest(quantity - new.quantity, 0),
        reserved_quantity = greatest(reserved_quantity - new.quantity, 0),
        status = case when greatest(quantity - new.quantity, 0) = 0
                      then 'sold_out'::public.listing_status
                      else status end
    where id = new.listing_id;

    new.completed_at := coalesce(new.completed_at, now());
  end if;

  return new;
end;
$$;

drop trigger if exists sync_inventory_after_order_status_trigger on public.orders;
create trigger sync_inventory_after_order_status_trigger
  before update of status on public.orders
  for each row execute function public.sync_inventory_after_order_status();

create or replace function public.sync_order_from_shipment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_order public.orders;
begin
  if new.status is distinct from old.status then
    insert into public.shipment_events(shipment_id, status, message, created_by)
    values (
      new.id,
      new.status,
      coalesce(new.note, 'Shipment status updated'),
      (select auth.uid())
    );

    update public.orders
    set status = case new.status
      when 'scheduled'::public.shipment_status then 'pickup_scheduled'::public.order_status
      when 'picked_up'::public.shipment_status then 'picked_up'::public.order_status
      when 'in_transit'::public.shipment_status then 'in_transit'::public.order_status
      when 'delivered'::public.shipment_status then 'delivered'::public.order_status
      when 'cancelled'::public.shipment_status then 'cancelled'::public.order_status
      else status
    end
    where id = new.order_id
    returning * into target_order;

    perform public.notify_user(
      target_order.buyer_id,
      'Cập nhật giao hàng',
      'Trạng thái mới: ' || new.status::text,
      'shipment', new.id
    );

    perform public.notify_user(
      target_order.seller_id,
      'Cập nhật giao hàng',
      'Trạng thái mới: ' || new.status::text,
      'shipment', new.id
    );
  end if;

  return new;
end;
$$;

drop trigger if exists sync_order_from_shipment_trigger on public.shipments;
create trigger sync_order_from_shipment_trigger
  after update of status on public.shipments
  for each row execute function public.sync_order_from_shipment();

-- updated_at triggers

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'organizations', 'profiles', 'warehouses', 'listings',
    'purchase_requests', 'logistics_partners', 'logistics_quotes',
    'orders', 'shipments', 'payments'
  ] loop
    execute format('drop trigger if exists set_updated_at_trigger on public.%I', table_name);
    execute format(
      'create trigger set_updated_at_trigger before update on public.%I '
      'for each row execute function public.set_updated_at()',
      table_name
    );
  end loop;
end $$;

-- =========================================================
-- 7. MARKETPLACE VIEW
-- =========================================================

create or replace view public.marketplace_listings
with (security_invoker = true)
as
select
  l.id,
  l.product_name,
  l.description,
  l.available_quantity,
  l.unit,
  l.unit_price,
  l.negotiable,
  l.condition_text,
  l.manufacturing_date,
  l.expiry_date,
  l.location_text,
  l.created_at,
  c.id as category_id,
  c.name as category_name,
  o.id as seller_organization_id,
  o.name as seller_organization_name
from public.listings l
join public.categories c on c.id = l.category_id
join public.organizations o on o.id = l.seller_organization_id
where l.status = 'approved'::public.listing_status
  and l.available_quantity > 0;

-- =========================================================
-- 8. ROW LEVEL SECURITY
-- =========================================================

alter table public.organizations enable row level security;
alter table public.profiles enable row level security;
alter table public.warehouses enable row level security;
alter table public.categories enable row level security;
alter table public.listings enable row level security;
alter table public.listing_media enable row level security;
alter table public.purchase_requests enable row level security;
alter table public.logistics_partners enable row level security;
alter table public.logistics_quotes enable row level security;
alter table public.orders enable row level security;
alter table public.shipments enable row level security;
alter table public.shipment_events enable row level security;
alter table public.payments enable row level security;
alter table public.notifications enable row level security;

-- Profiles
drop policy if exists profiles_select_policy on public.profiles;
create policy profiles_select_policy on public.profiles
for select to authenticated
using (id = (select auth.uid()) or public.is_host());

drop policy if exists profiles_update_policy on public.profiles;
create policy profiles_update_policy on public.profiles
for update to authenticated
using (id = (select auth.uid()) or public.is_host())
with check (id = (select auth.uid()) or public.is_host());

-- Organizations
drop policy if exists organizations_select_policy on public.organizations;
create policy organizations_select_policy on public.organizations
for select to anon, authenticated
using (
  public.is_host()
  or created_by = (select auth.uid())
  or id = (select organization_id from public.profiles where id = (select auth.uid()))
  or exists (
    select 1 from public.listings l
    where l.seller_organization_id = organizations.id
      and l.status = 'approved'::public.listing_status
  )
);

drop policy if exists organizations_insert_policy on public.organizations;
create policy organizations_insert_policy on public.organizations
for insert to authenticated
with check (created_by = (select auth.uid()));

drop policy if exists organizations_update_policy on public.organizations;
create policy organizations_update_policy on public.organizations
for update to authenticated
using (created_by = (select auth.uid()) or public.is_host())
with check (created_by = (select auth.uid()) or public.is_host());

-- Warehouses
drop policy if exists warehouses_select_policy on public.warehouses;
create policy warehouses_select_policy on public.warehouses
for select to authenticated
using (
  public.is_host()
  or organization_id = (select organization_id from public.profiles where id = (select auth.uid()))
);

drop policy if exists warehouses_insert_policy on public.warehouses;
create policy warehouses_insert_policy on public.warehouses
for insert to authenticated
with check (
  organization_id = (select organization_id from public.profiles where id = (select auth.uid()))
  or public.is_host()
);

drop policy if exists warehouses_update_policy on public.warehouses;
create policy warehouses_update_policy on public.warehouses
for update to authenticated
using (
  organization_id = (select organization_id from public.profiles where id = (select auth.uid()))
  or public.is_host()
)
with check (
  organization_id = (select organization_id from public.profiles where id = (select auth.uid()))
  or public.is_host()
);

-- Categories
drop policy if exists categories_read_policy on public.categories;
create policy categories_read_policy on public.categories
for select to anon, authenticated using (is_active = true or public.is_host());

drop policy if exists categories_host_write_policy on public.categories;
create policy categories_host_write_policy on public.categories
for all to authenticated
using (public.is_host())
with check (public.is_host());

-- Listings
drop policy if exists listings_select_policy on public.listings;
create policy listings_select_policy on public.listings
for select to anon, authenticated
using (
  status = 'approved'::public.listing_status
  or seller_id = (select auth.uid())
  or public.is_host()
);

drop policy if exists listings_insert_policy on public.listings;
create policy listings_insert_policy on public.listings
for insert to authenticated
with check (
  public.current_app_role() = 'seller'::public.app_role
  and seller_id = (select auth.uid())
  and seller_organization_id = (
    select organization_id from public.profiles where id = (select auth.uid())
  )
  and exists (
    select 1 from public.warehouses w
    where w.id = warehouse_id and w.organization_id = seller_organization_id
  )
);

drop policy if exists listings_update_policy on public.listings;
create policy listings_update_policy on public.listings
for update to authenticated
using (seller_id = (select auth.uid()) or public.is_host())
with check (
  public.is_host()
  or (
    seller_id = (select auth.uid())
    and seller_organization_id = (
      select organization_id from public.profiles where id = (select auth.uid())
    )
    and exists (
      select 1 from public.warehouses w
      where w.id = warehouse_id and w.organization_id = seller_organization_id
    )
  )
);

drop policy if exists listings_delete_policy on public.listings;
create policy listings_delete_policy on public.listings
for delete to authenticated
using (
  public.is_host()
  or (
    seller_id = (select auth.uid())
    and status in ('draft'::public.listing_status, 'rejected'::public.listing_status)
  )
);

-- Listing media
drop policy if exists listing_media_select_policy on public.listing_media;
create policy listing_media_select_policy on public.listing_media
for select to anon, authenticated
using (
  exists (
    select 1 from public.listings l
    where l.id = listing_media.listing_id
      and (
        l.status = 'approved'::public.listing_status
        or l.seller_id = (select auth.uid())
        or public.is_host()
      )
  )
);

drop policy if exists listing_media_insert_policy on public.listing_media;
create policy listing_media_insert_policy on public.listing_media
for insert to authenticated
with check (
  uploaded_by = (select auth.uid())
  and exists (
    select 1 from public.listings l
    where l.id = listing_media.listing_id
      and l.seller_id = (select auth.uid())
  )
);

drop policy if exists listing_media_delete_policy on public.listing_media;
create policy listing_media_delete_policy on public.listing_media
for delete to authenticated
using (
  uploaded_by = (select auth.uid())
  or public.is_host()
);

-- Purchase requests
drop policy if exists purchase_requests_select_policy on public.purchase_requests;
create policy purchase_requests_select_policy on public.purchase_requests
for select to authenticated
using (
  buyer_id = (select auth.uid())
  or seller_id = (select auth.uid())
  or host_id = (select auth.uid())
  or public.is_host()
);

drop policy if exists purchase_requests_insert_policy on public.purchase_requests;
create policy purchase_requests_insert_policy on public.purchase_requests
for insert to authenticated
with check (
  public.current_app_role() = 'customer'::public.app_role
  and buyer_id = (select auth.uid())
);

drop policy if exists purchase_requests_host_update_policy on public.purchase_requests;
create policy purchase_requests_host_update_policy on public.purchase_requests
for update to authenticated
using (public.is_host())
with check (public.is_host());

-- Logistics partners: host manages; participants can see partner tied to their orders/quotes.
drop policy if exists logistics_partners_select_policy on public.logistics_partners;
create policy logistics_partners_select_policy on public.logistics_partners
for select to authenticated
using (
  public.is_host()
  or exists (
    select 1
    from public.logistics_quotes q
    join public.purchase_requests pr on pr.id = q.purchase_request_id
    where q.logistics_partner_id = logistics_partners.id
      and (pr.buyer_id = (select auth.uid()) or pr.seller_id = (select auth.uid()))
  )
);

drop policy if exists logistics_partners_host_write_policy on public.logistics_partners;
create policy logistics_partners_host_write_policy on public.logistics_partners
for all to authenticated
using (public.is_host())
with check (public.is_host());

-- Logistics quotes
drop policy if exists logistics_quotes_select_policy on public.logistics_quotes;
create policy logistics_quotes_select_policy on public.logistics_quotes
for select to authenticated
using (
  public.is_host()
  or exists (
    select 1 from public.purchase_requests pr
    where pr.id = logistics_quotes.purchase_request_id
      and (pr.buyer_id = (select auth.uid()) or pr.seller_id = (select auth.uid()))
  )
);

drop policy if exists logistics_quotes_host_write_policy on public.logistics_quotes;
create policy logistics_quotes_host_write_policy on public.logistics_quotes
for all to authenticated
using (public.is_host())
with check (public.is_host());

-- Orders
drop policy if exists orders_select_policy on public.orders;
create policy orders_select_policy on public.orders
for select to authenticated
using (
  buyer_id = (select auth.uid())
  or seller_id = (select auth.uid())
  or host_id = (select auth.uid())
  or public.is_host()
);

drop policy if exists orders_host_write_policy on public.orders;
create policy orders_host_write_policy on public.orders
for all to authenticated
using (public.is_host())
with check (public.is_host());

-- Shipments
drop policy if exists shipments_select_policy on public.shipments;
create policy shipments_select_policy on public.shipments
for select to authenticated
using (
  public.is_host()
  or exists (
    select 1 from public.orders o
    where o.id = shipments.order_id
      and (o.buyer_id = (select auth.uid()) or o.seller_id = (select auth.uid()))
  )
);

drop policy if exists shipments_host_write_policy on public.shipments;
create policy shipments_host_write_policy on public.shipments
for all to authenticated
using (public.is_host())
with check (public.is_host());

-- Shipment events
drop policy if exists shipment_events_select_policy on public.shipment_events;
create policy shipment_events_select_policy on public.shipment_events
for select to authenticated
using (
  public.is_host()
  or exists (
    select 1
    from public.shipments s
    join public.orders o on o.id = s.order_id
    where s.id = shipment_events.shipment_id
      and (o.buyer_id = (select auth.uid()) or o.seller_id = (select auth.uid()))
  )
);

drop policy if exists shipment_events_host_write_policy on public.shipment_events;
create policy shipment_events_host_write_policy on public.shipment_events
for all to authenticated
using (public.is_host())
with check (public.is_host());

-- Payments
drop policy if exists payments_select_policy on public.payments;
create policy payments_select_policy on public.payments
for select to authenticated
using (
  payer_id = (select auth.uid())
  or public.is_host()
  or exists (
    select 1 from public.orders o
    where o.id = payments.order_id and o.seller_id = (select auth.uid())
  )
);

drop policy if exists payments_host_write_policy on public.payments;
create policy payments_host_write_policy on public.payments
for all to authenticated
using (public.is_host())
with check (public.is_host());

-- Notifications
drop policy if exists notifications_select_policy on public.notifications;
create policy notifications_select_policy on public.notifications
for select to authenticated
using (user_id = (select auth.uid()));

drop policy if exists notifications_update_policy on public.notifications;
create policy notifications_update_policy on public.notifications
for update to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

-- =========================================================
-- 9. STORAGE BUCKETS + POLICIES
-- =========================================================

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images', 'product-images', true, 5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'listing-documents', 'listing-documents', false, 10485760,
  array['application/pdf', 'image/jpeg', 'image/png']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Product images are publicly readable.
drop policy if exists product_images_public_read on storage.objects;
create policy product_images_public_read on storage.objects
for select to anon, authenticated
using (bucket_id = 'product-images');

-- Seller uploads under: product-images/<auth.uid()>/<filename>
drop policy if exists product_images_seller_insert on storage.objects;
create policy product_images_seller_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'product-images'
  and public.current_app_role() = 'seller'::public.app_role
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists product_images_owner_update on storage.objects;
create policy product_images_owner_update on storage.objects
for update to authenticated
using (
  bucket_id = 'product-images'
  and ((storage.foldername(name))[1] = (select auth.uid())::text or public.is_host())
)
with check (
  bucket_id = 'product-images'
  and ((storage.foldername(name))[1] = (select auth.uid())::text or public.is_host())
);

drop policy if exists product_images_owner_delete on storage.objects;
create policy product_images_owner_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'product-images'
  and ((storage.foldername(name))[1] = (select auth.uid())::text or public.is_host())
);

-- Listing documents are private to the seller and hosts.
drop policy if exists listing_documents_private_read on storage.objects;
create policy listing_documents_private_read on storage.objects
for select to authenticated
using (
  bucket_id = 'listing-documents'
  and ((storage.foldername(name))[1] = (select auth.uid())::text or public.is_host())
);

drop policy if exists listing_documents_seller_insert on storage.objects;
create policy listing_documents_seller_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'listing-documents'
  and public.current_app_role() = 'seller'::public.app_role
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists listing_documents_owner_update on storage.objects;
create policy listing_documents_owner_update on storage.objects
for update to authenticated
using (
  bucket_id = 'listing-documents'
  and ((storage.foldername(name))[1] = (select auth.uid())::text or public.is_host())
)
with check (
  bucket_id = 'listing-documents'
  and ((storage.foldername(name))[1] = (select auth.uid())::text or public.is_host())
);

drop policy if exists listing_documents_owner_delete on storage.objects;
create policy listing_documents_owner_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'listing-documents'
  and ((storage.foldername(name))[1] = (select auth.uid())::text or public.is_host())
);

-- =========================================================
-- 10. PRIVILEGES
-- =========================================================

grant usage on schema public to anon, authenticated;

grant select on public.categories, public.listings, public.listing_media,
  public.organizations, public.marketplace_listings to anon;

grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on public.marketplace_listings to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke execute on function public.host_review_listing(uuid, boolean, text) from public, anon;
revoke execute on function public.host_assign_purchase_request(uuid) from public, anon;
revoke execute on function public.seller_respond_purchase_request(uuid, boolean, numeric, numeric, text) from public, anon;
revoke execute on function public.host_add_logistics_quote(uuid, uuid, numeric, timestamptz, timestamptz, timestamptz, text) from public, anon;
revoke execute on function public.buyer_confirm_logistics_quote(uuid, uuid) from public, anon;
revoke execute on function public.buyer_cancel_purchase_request(uuid, text) from public, anon;
revoke execute on function public.host_create_order(uuid, numeric) from public, anon;

grant execute on function public.current_app_role() to anon, authenticated;
grant execute on function public.is_host() to anon, authenticated;
grant execute on function public.host_review_listing(uuid, boolean, text) to authenticated;
grant execute on function public.host_assign_purchase_request(uuid) to authenticated;
grant execute on function public.seller_respond_purchase_request(uuid, boolean, numeric, numeric, text) to authenticated;
grant execute on function public.host_add_logistics_quote(uuid, uuid, numeric, timestamptz, timestamptz, timestamptz, text) to authenticated;
grant execute on function public.buyer_confirm_logistics_quote(uuid, uuid) to authenticated;
grant execute on function public.buyer_cancel_purchase_request(uuid, text) to authenticated;
grant execute on function public.host_create_order(uuid, numeric) to authenticated;

-- Internal helper functions should not be called directly by clients.
revoke execute on function public.notify_user(uuid, text, text, text, uuid) from public, anon, authenticated;
revoke execute on function public.notify_hosts(text, text, text, uuid) from public, anon, authenticated;

commit;

-- =========================================================
-- POST-INSTALL: CREATE THE FIRST HOST
-- =========================================================
-- 1) Create the account in Supabase Auth (Dashboard > Authentication > Users).
-- 2) Run the statement below using that account's email:
--
-- update public.profiles
-- set role = 'host'
-- where email = 'host@stockflow.vn';
--
-- Public signup metadata example:
-- seller:   { "role": "seller", "full_name": "Seller Name" }
-- customer: { "role": "customer", "full_name": "Buyer Name" }
-- Any public request for role=host is intentionally converted to customer.